AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20
